#Minedown compatible!
#%PLAYER% will be replaced with the name of the player.
#%COUNT% will be replaced with what number player they are.
commandPrefix: "&rainbow&[ES]"
welcomeMessage: ""
personalMessages:
  - ""
firstTimeWelcomeMessage: "&8&l[&a{COUNT}&8&l] &f{PLAYER} has joined for the first time ever."
firstTimePersonalMessages:
  - ""
  - ""
  - ""
